-- 001-initial-schema.sql
-- Criação da tabela de carrinho temporário
create table j_carrinho_temp (
    jct_id          number
        generated by default as identity
    primary key,
    jct_session_id  varchar2(100) not null,
    jct_proid       number not null,
    jct_quantidade  number not null,
    jct_data_adicao timestamp default current_timestamp,
    jct_cnpj_temp   varchar2(20)
);

-- Ajustes na tabela J_ENDERE (clientes)
    alter table j_endere add (
    jnd_senha_hash           varchar2(255),
    jnd_ativo_portal         number(1) default 0,
    jnd_data_cadastro_portal timestamp
);